### ISSUE TITLE
use of internal package github.com/huobirdcenter/huobi_golang/internal/model not allowed

### ISSUE THREAD

**Issue by xf005** [HuobiRDCenter/huobi_Golang#1]
use of internal package not allowed

**Comment by eynzhang** [comment]
@xf005 , could you tell us how you use the SDK and why do you want to import internal package?

The purpose of internal package, as the name indiated, is used internally, you don’t need to care about the internal package. What you need to import is the “pkg” package.

**Comment by xf005** [comment]
Go module management project,reuse websocket method in cmd package. It's confusing to use the websocket method from the example in my project.

**Comment by eynzhang** [comment]
The example just shows how to use the “client” package, you should import the client package in your own project, and write something similar with the examples.

Today we introduce the go modules and updated the README file, it is easier to import the package in your own project now.

**Comment by simpdo** [comment]
when i create accountwebsocketclient.RequestAccountWebSocketV1Client , the client method SetHandler first param websocketclientbase.AuthenticationV1ResponseHandler  which define func(resp *model.WebSocketV1AuthenticationResponse), the function param resp used internal pkg

**Comment by eynzhang** [comment]
@simpdo I noticed that issue and I will do a fix. Thanks for the feedback.

**Comment by eynzhang** [comment]
We have fixed this issue by moving websocket authentication response from internal to pkg, now you can get latest code from master branch.

**Comment by xyths** [comment]
@eynzhang i have the same issue today, when i update to latest code, it fixed, thank you.
