### ISSUE TITLE
config.go miss SecretKey

### ISSUE THREAD

**Issue by JackyCZJ** [HuobiRDCenter/huobi_Golang#11]

**Comment by huobiapi** [comment]
@JackyCZJ , this is the design intent and described in REAMDE:

_Create **key.go** into your **config** folder (package). The purpose of this file is to prevent submitting SecretKey into repository by accident, so this file is already added in the *.gitignore* file._ 

Therefore if you download the SDK and want to run the example, you should create the key.go manually. If you just import the SDK, then you can manage the secretKey by yourself and stored on proper place
