### ISSUE TITLE
TradeTick.Data.Id is overflow

### ISSUE THREAD

**Issue by kingwrcy** [HuobiRDCenter/huobi_Golang#12]
GetHistoricalTrade error: json: cannot unmarshal number 10043412649746196623382279 into Go struct field .data.Data.id of type int64

**Comment by eynzhang** [comment]
@kingwrcy Thanks for the feedback, this is resolved in master branch and tag [v2.2.1](https://github.com/HuobiRDCenter/huobi_Golang/releases/tag/v2.2.1)
