### ISSUE TITLE
Auth errors are silenced

### ISSUE THREAD

**Issue by filinvadim** [HuobiRDCenter/huobi_Golang#16]
I don't receive any messages if auth wasn't successful.

Problem is here: https://github.com/HuobiRDCenter/huobi_Golang/blob/75de5c6fcc0ed1917ef0d9e3a00c7b315f427224/pkg/model/auth/websocketv1authenticationresponse.go#L14

Have:
```go
func (p *WebSocketV1AuthenticationResponse) IsAuth() bool {
	return p.Op == "auth" && p.ErrorCode == 0
}
```

Need:
```go
func (p *WebSocketV1AuthenticationResponse) IsAuth() bool {
	return p.Op == "auth"
}
```

**Comment by eynzhang** [comment]
@filinvadim thanks for your feedback, we have fixed this in latest master branch.
