### ISSUE TITLE
Cannot unmarshal number into Go struct field RequestOrdersV1Response.err-code of type string

### ISSUE THREAD

**Issue by filinvadim** [HuobiRDCenter/huobi_Golang#17]
Message:
`{"op":"req","ts":1598615344364,"topic":"orders.list","err-code":10021,"cid":"","err-msg":"req orders.list query error:Please enter a valid account-id."}`

RequestOrdersV1Response.ErrCode field must be integer.

**Comment by eynzhang** [comment]
@filinvadim thanks for your feedback, it is fixed in latest master branch.

Reminder: the websocket v1 will be obsolete, it is suggest you use websocket v2.
