### ISSUE TITLE
Responses with errors are silenced

### ISSUE THREAD

**Issue by filinvadim** [HuobiRDCenter/huobi_Golang#18]
By this line:
https://github.com/HuobiRDCenter/huobi_Golang/blob/75de5c6fcc0ed1917ef0d9e3a00c7b315f427224/pkg/client/websocketclientbase/websocketv1clientbase.go#L238

Need to remove it.

**Comment by eynzhang** [comment]
@filinvadim thanks for your feedback, the condition is removed so that the errors can be exposed.

Reminder: the websocket v1 will be obsolete, it is suggest you use websocket v2.
