### ISSUE TITLE
*OrderClient.CancelOrderById doesn't return order-state field

### ISSUE THREAD

**Issue by choleraehyq** [HuobiRDCenter/huobi_Golang#26]
Referring to https://huobiapi.github.io/docs/spot/v1/cn/#4e53c0fccd, /v1/order/orders/{order-id}/submitcancel should return an "order-state" field when error occurs.

**Comment by eynzhang** [comment]
@choleraehyq thanks for the feedback, the field "order-state” now is added and you can get it in latest master branch.
