### ISSUE TITLE
the getrequest package could not be found 

### ISSUE THREAD

**Issue by chris-gqz** [HuobiRDCenter/huobi_Golang#27]
in readme

Market data
Candlestick/KLine
client := new(client.MarketClient).Init(config.Host)
optionalRequest := getrequest.GetCandlestickOptionalRequest{Period: getrequest.MIN1, Size: 10}
resp, err := client.GetCandlestick("btcusdt", optionalRequest)

the getrequest package could not be found

**Comment by eynzhang** [comment]
@chris-gqz thanks for your feedback, the README is out of date and now it is updated in latest master branch.
