### ISSUE TITLE
代码发布后麻烦先测试一下

### ISSUE THREAD

**Issue by chris-gqz** [HuobiRDCenter/huobi_Golang#34]
![image](https://user-images.githubusercontent.com/19997040/107491558-488f9c80-6bc6-11eb-8201-ab0f442968fb.png)

**Comment by eynzhang** [comment]
@chris-gqz 您好，import中的路径是go mod自动生成的，可以正常运行。您那边遇到了什么问题？

**Comment by eynzhang** [comment]
@chris-gqz 您的问题会关闭，此问题已经在https://github.com/HuobiRDCenter/huobi_Golang/issues/15 提交过。
