### ISSUE TITLE
websocket 接口很容易出现重新链接

### ISSUE THREAD

**Issue by xtls2** [HuobiRDCenter/huobi_Golang#36]
websocket 接口很容易出现重新链接 请检查一下（我自己用golang实现的就不会出现这个问题）

**Comment by xtls2** [comment]
reconnect 机制有问题

**Comment by eynzhang** [comment]
@xtls2 Thanks for your feedback, the reconnection failure is introduced in previous code change, now it is fixed and updated to latest master branch.
