### ISSUE TITLE
{"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature not valid: Verification failure [校验失败]","data":null}

### ISSUE THREAD

**Issue by simpdo** [HuobiRDCenter/huobi_Golang#4]
first i get accont information by client.AccountClient ,when i recieve the response, i use the same account client  instance  to get the account balance , this time the response is a error 

`{"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature not valid: Verification failure [校验失败]","data":null}`

but when i  change the code like that 
`
func (p *Signer) sign(payload string) string {
	p.hash.Write([]byte(payload))
	result := base64.StdEncoding.EncodeToString(p.hash.Sum(nil))

	p.hash.Reset()
	return result
}`
then there is no error，but i dont know whether it‘s correct

**Comment by eynzhang** [comment]
@simpdo , thanks for your feedback, I have fixed this idempotence issue. You can get latest code from master branch.
