### ISSUE TITLE
when orderwebsocketclient package("Websocket Asset and Order (v2)") add support for "orders.$symbol"?

### ISSUE THREAD

**Issue by titilami** [HuobiRDCenter/huobi_Golang#6]
i notice that in v1 version supported subscribe "orders.$symbol.update"   in the example "orderwebsocketclientexample.go --> subOrderUpdateV1()", but it will to be  obsoleted.
subOrderUpdateV2() only supported subscribe "accounts.update#".
i can not find "orders#${symbol}" in v2 version in golang sdk. https://huobiapi.github.io/docs/spot/v1/en/#subscribe-order-updates

**Comment by eynzhang** [comment]
@titilami we just released [https://github.com/HuobiRDCenter/huobi_Golang/releases/tag/v2.1.1](v2.1.1) today to include websocket v2 order update. You can get it now.

**Comment by titilami** [comment]
ok,thx, please close the issue.
